miapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<articulo_id>[0-9]+)/$', views.detalleArticulo, name='detalleArticulo'),
    url(r'^(?P<articulo_id>[0-9]+)/resultados/$', views.resultados, name='resultados'),
    url(r'^(?P<articulo_id>[0-9]+)/votarPositivo/$', views.votarPositivo, name='votarPositivo'),
    url(r'^(?P<articulo_id>[0-9]+)/votarNegativo/$', views.votarNegativo, name='votarNegativo'),
    url(r'^articulo/new/$', views.new_articulo, name='new_articulo'),
]

miproyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'miproyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^miapp/', include('miapp.urls', namespace='miapp')),
    url(r'^admin/', include(admin.site.urls)),
]

miapp/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Reportero(models.Model):
    nombre_completo = models.CharField(max_length=50)

    def __unicode__(self):
        return u'%s' % self.nombre_completo

class Articulo(models.Model):
    fecha_pub = models.DateTimeField(auto_now_add=True)
    encabezado = models.CharField(blank=False, max_length=200)
    contenido = models.TextField(blank=False,)
    reportero = models.ForeignKey(Reportero, blank=False)
    votos = models.IntegerField(default=0)

# Sí es python3 sería __str__
    def __unicode__(self): 
        return u'%s' % self.encabezado

    def fue_publicado_recientemente(self):
        return self.fecha_pub >= timezone.now() - datetime.timedelta(days=1)
    fue_publicado_recientemente.admin_order_field = 'fecha_pub'
    fue_publicado_recientemente.boolean = True
    fue_publicado_recientemente.short_description = '¿Fue publicado recientemente?'

miapp/forms.py
from django import forms
from .models import Articulo

class ArticuloForm(forms.ModelForm):
      
      class Meta:
	model = Articulo
	fields = ('encabezado','contenido','reportero',)

miapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.template import RequestContext, loader
from .models import Reportero, Articulo
from .forms import ArticuloForm
from django.utils import timezone

# Create your views here.
def index(request):
    lista_ultimos_articulos = Articulo.objects.order_by('-votos')[:5]
    # Retornar vista sin template
    # salida = ', '.join([articulo.encabezado for articulo in lista_ultimos_articulos])
    # return HttpResponse(salida)

    # Retornar vista con template metodo largo
    # template  = loader.get_template('miapp/index.html')
    # context = RequestContext(request, {
    #	'lista_ultimos_articulos': lista_ultimos_articulos,
    # })
    #return HttpResponse(template.render(context))

    # Retornar vista con template metodo corto (Recomendado)
    context = {'lista_ultimos_articulos': lista_ultimos_articulos, 'numero': 20}
    return render(request, 'miapp/index.html', context)


def detalleArticulo(request, articulo_id):
    try:
	articulo = Articulo.objects.get(pk=articulo_id)
    except Articulo.DoesNotExist:
	raise Http404('El Articulo no existe!')
    return render(request, 'miapp/detallesArticulo.html', {
        'articulo': articulo,
        'sin_votar': True, 
    })


def resultados(request):
    return HttpResponse('Hola')


def votarPositivo(request, articulo_id):
    articulo = Articulo.objects.get(pk=articulo_id)
    articulo.votos += 1
    articulo.save()
    return render(request, 'miapp/detallesArticulo.html', {
        'articulo': articulo,
        'sin_votar': False, 
    })    

def votarNegativo(request, articulo_id):
    articulo = Articulo.objects.get(pk=articulo_id)
    articulo.votos -= 1
    articulo.save()
    return render(request, 'miapp/detallesArticulo.html', {
        'articulo': articulo,
        'sin_votar': False, 
    })


def new_articulo(request):
    if request.method == "POST":
	form = ArticuloForm(request.POST)
	if form.is_valid():
	   articulo = form.save()
	 # post.autor = request.user
	   articulo.save()
	   return render(request, 'miapp/detallesArticulo.html', {
               'articulo': articulo,
               'sin_votar': False,
          })

    else:
	form = ArticuloForm()
    return render(request, 'miapp/new_articulo.html', {'form':form})

miapp/templates/miapp/detallesArticulo.html
{% load staticfiles %}
<h3>{{articulo.encabezado }}</h3>
<p>{{ articulo.contenido }}</p>
<p>Publicado el: {{ articulo.fecha_pub|date:"j" }} de {{ articulo.fecha_pub|date:"F" }} del {{ articulo.fecha_pub|date:"Y" }} 
a las {{ articulo.fecha_pub|date:"f A" }}</p>

{% if sin_votar %}
<a href="{% url 'miapp:votarPositivo' articulo.id %}">
   <img src="{% static 'img/upvote.png' %}" height="30" width="30" alt="Votar Positivo!"/>
</a>

<a href="{% url 'miapp:votarNegativo' articulo.id %}">
   <img src="{% static 'img/downvote.png' %}" height="30" width="30" alt="votar Negativo!"/>
</a>
{% else %}
<b>Gracias por votar!</b></br></br>
<a href="{% url 'miapp:index' %}">Regresar al inicio</a>

{% endif %}

miapp/templates/miapp/index.html
{% if lista_ultimos_articulos %}
	<ul>
	{% for articulo in lista_ultimos_articulos %}
	     <li><a href="{% url 'miapp:detalleArticulo' articulo.id %}">{{ articulo.encabezado }}</a> 
		{% if articulo.votos == 0 %}
		[{{ articulo.votos }}]
		{% endif%}

		{% if articulo.votos > 0 %}
		[<span style="color:green">{{ articulo.votos }}</span>]
		{% endif %}

		{% if articulo.votos < 0 %}
		[<span style="color:red">{{ articulo.votos }}</span>]
		{% endif %}
	     </li>
	{% endfor %}
	</ul>
{% else %}
	<p>No hay articulos disponibles! </p>
{% endif %}

<p><a href="{% url 'miapp:new_articulo' %}"> Registra un Articulo </a></p>

miapp/templates/miapp/new_articulo.html
<h1>Nuevo Reportero</h1>
<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <button type="submit">Registrar</button>
</form>